### ISSUE TITLE
autoplay failed.

### ISSUE THREAD

**Issue by jungleyu** [archriss/react-native-snap-carousel#150]
When I set autoplay to true, it just slide to next item and then stopped

**Comment by bd-arc** [comment]
Have you tried version `3.2.1`? It should fix this issue introduced in `3.2.0`. Can you confirm that it works as expected?

**Comment by jungleyu** [comment]
It works well on version 3.2.1, thank you!

**Comment by albertosgr** [comment]
I still have problems with auto play on android with 3.2.1 version.

**Comment by bd-arc** [comment]
Did you take a look at [this note](https://github.com/archriss/react-native-snap-carousel#unreliable-callbacks) from the doc?

**Comment by albertosgr** [comment]
Autoplay fails when enableMomentum = true.  If I set it to false, its working. Let me do some more tests on it, since its binded with a pagination control with tap enabled (autoplay + tap on pagination)

**Comment by bd-arc** [comment]
Oh, you might be onto something: with the new callback mechanism, I may have forgotten to handle everything properly when `enableMomentum` is set to `true`... I'll shortly take a look at it.

**Comment by bd-arc** [comment]
@albertosgr Indeed, I did make a mistake while refactoring. [This commit](https://github.com/archriss/react-native-snap-carousel/commit/d0a10517dbf6053cc02b30859b7cb38eb2181f48) fixes the issue ;-)

**Comment by bd-arc** [comment]
@albertosgr The fix is available in version `3.2.2` ;-)

**Comment by albertosgr** [comment]
Thank you.

**Comment by lichenglu** [comment]
Thank you for the great work!

I am using 3.3.3 now, but I am having issues of using autoplay along with loop (enableMomentum is set to false). The behavior is when it first starts to autoplay after 5 seconds of default delay, it starts to with a blank/white view, and if you start to scroll, it starts to jump around. You will need to scroll a few times until it works properly. If I disable `loop`, then everything works great.

Any idea on this?

**Comment by lichenglu** [comment]
Hmm...briefly went through the code of carousel. It seems the issue I mentioned has something to do with `_getFirstItem`. As when `loop` is enabled, the first item returned is `index + loopClonesPerSide`. If I adjust the `firstItem` prop to be `sliderFirstItem - loopClonesPerSide` where `loopClonesPerSide` is smaller than data's length, then things work out fine.
@bd-arc

**Comment by bd-arc** [comment]
Hi @lichenglu,

I haven't been able to reproduce the issue you describe. Can you try to build [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)? The first carousel in it uses both autoplay and loop, and it works flawlessly on every device I've tested it on.

In the meantime, can you also give version `3.3.4` a try? It fixes an issue that sometimes arise when `loopClonesPerSide` is greater than data length.

**Comment by leonardo1294** [comment]
auto play for when I touch an image and scroll the screen, any help on the problem?

**Comment by sridix** [comment]
scroll screen disable autoplay

**Comment by wahas-mughal** [comment]
In order to work autoplay, you need loop and enableSnap props set to be true besides autoplay.
