### ISSUE TITLE
Layout is messed up with RTL devices

### ISSUE THREAD

**Issue by dyaacov** [archriss/react-native-snap-carousel#38]
The example from google play doesn't work on LG G2

**Comment by bd-arc** [comment]
@dyaacov Hi! Thank you for letting us now. Could you be a bit more specific? Is the app crashing at startup? Are some parts of the app unavailable? Is it another kind of issue?

**Comment by dyaacov** [comment]
Hi,
Sorry for the late response.
The app doesn't crash, the carousel doesn't work nor doesn't look good.
See attached screenshots (this is from your demo app in Google Play
archriss)

*carousel_1.png*: this is how it looks when you open the app
*carousel_2. png*: when you click next/previous, all the images disappear

**Comment by bd-arc** [comment]
@dyaacov Thank you for getting back to me!
It seems your screenshots didn't make it to GitHub ;) Would you mind hosting them online (on [imgur](http://imgur.com/) for example)?

**Comment by dyaacov** [comment]
http://i.imgur.com/LPJaUbo.png

http://i.imgur.com/aGhzfAS.png

**Comment by bd-arc** [comment]
@dyaacov Thank you for taking the time to upload these screenshots. Now begins the painful journey of trying to reproduce the bug on our devices ;)

**Comment by dyaacov** [comment]
Thank you.
I tested LG g2 and g3, same results.
On Nexus 5x it works fine.
I hope you can provide a fix soon cause I really want to use this feature
in my new app.
Maybe a wrong calculation of sizes due to different resolutions. Let me
know if you need my assistance. I can test on several different devices.

May the force be with you!
Dekel

**Comment by bd-arc** [comment]
@dyaacov We've tried the app on a LG G3 and weren't able to reproduce the issue. I fear a buggy React Native's `ScrollView` implementation on some Android versions :-( That's why we're currently considering implementing our own `PanResponder` (see #40), but this requires major developments.

Can you share the Android versions on which you've tried the app, and specify the ones that were buggy?

**Comment by dyaacov** [comment]
Android 5.0, core 3.4.0, software v20n-456-01
Android 4.4.2, core 3.4.0, software d80220a-isr-xx

**Comment by bd-arc** [comment]
@dyaacov Just a quick update: I wasn't able to reproduce the issue, either on a simulator or a real device. Still investigating though ;)

**Comment by dyaacov** [comment]
Have you tried on LG devices?
It doesn't work on 3 different LG devices.

**Comment by bd-arc** [comment]
@dyaacov I've tried on the only one that was around, a LG G3, without seeing any issue. My guess is that there is something wrong with `ScrollView` implementation on some specific Android devices, but I need to be able to reproduce the bug to investigate further.

I'll look around for other LG devices.

**Comment by dyaacov** [comment]
You can send me apk with a lot of debug logs and I will reproduce and send
you the logs

**Comment by bd-arc** [comment]
@dyaacov That's an idea, thanks! I'll prepare a debug apk as soon as I can (not before a few days I'm afraid).

In the meantime, and if this is not too much trouble, a short video of the issue might help figuring out what's happening.

**Comment by bd-arc** [comment]
@dyaacov Would you mind building the latest version of the example and tell me if you can still reproduce the issue on your devices?

I've made a few bug fixes in the latest release and also bumped the RN version of the example to the latest stable one; that might have helped ;)

**Comment by dyaacov** [comment]
Sorry, same issues. when you first open it, the first slide is adjusted to left and when you try to swipe everything is mess.

**Comment by bd-arc** [comment]
@dyaacov Thank you very much for the video! Thanks to it, I've finally understood the root of the issue. This has to do with left-to-right UI. If you change your settings to right-to-left, you'll see the issue vanish.

You can see that items are rendered left-to-right but that our snap calculations are applied right-to-left. I'll look into a fix as soon as possible.

**Comment by yaronlevi** [comment]
It is a known issue. ScrollView + RTL = bug.
https://github.com/facebook/react-native/issues/10852

**Comment by bd-arc** [comment]
@dyaacov @yaronlevi Good news! I've just published a new version of the plugin that adds RTL support and should resolve your issue.

As @yaronlevi stated, the issue had to do with React Native's RTL handling. I had to tweak a few things, so make sure to read [the notes](https://github.com/archriss/react-native-snap-carousel#rtl-support) about this feature.

Can you both confirm that this solves the issue for you?

**Comment by dyaacov** [comment]
Hi,
I still see the same issue as in my previous video.
I verified I got the latest Git changes.

:(

**Comment by bd-arc** [comment]
@dyaacov This is strange...

Two days ago, I was finally able to reproduce the issue with `I18nManager.forceRTL(true)`, and I've worked around it thanks to some heavy head-scratching.

I'm positive that this works since I've tested the fix on iOS and Android, on both emulators and real devices. Anyway, I'll triple-check tomorrow.

In the meantime, can you locally change [this line](https://github.com/archriss/react-native-snap-carousel/blob/master/example/package.json#L12) to `"react-native-snap-carousel": "2.1.0"`, run `npm install` in the `/example` folder and rebuild the example app? I myself had issues with npm's cache earlier and this helped.

**Comment by dyaacov** [comment]
YES!!!
1. I changed to "react-native-snap-carousel": "2.1.0"
2. removed node_modules and ran npm install again

Well done!
I'll do more testing in the next 2 days.

**Comment by bd-arc** [comment]
@dyaacov Good to hear! I'm closing the issue, but do not hesitate to keep me posted with the results of your tests ;)

**Comment by dyaacov** [comment]
Found another bug in **RTL** only.
First time you load the carousel, the first image is not in focus (gray color and same size as the other images)

**Comment by bd-arc** [comment]
@dyaacov I have faced this issue while implementing RTL support, but I got rid of it and haven't been able to reproduce it since then.

Are you talking about the first slide to the left or to the right?

**Comment by dyaacov** [comment]
The first active slide, I don't now what you mean by the first to the right
or to the left.
Another small bug, the slides are reversed order in RTL, I fixed locally it
by calling this.state.items.reverese if I'm in RTL

**Comment by bd-arc** [comment]
@dyaacov The reversed order is by design. I was assuming that, if you have an array of [1, 2, 3], you would expect slides to be rendered [3, 2, 1] so that they can be read from right to left in the same order as they would in a LTR layout. Was that a mistake?

**Comment by dyaacov** [comment]
In my design, the slides have timestamp so I want to present them order by
creation date, regardless RTL

**Comment by dyaacov** [comment]
I think you should not interfere in the slides order, each implementer
should order it according to his logic.

**Comment by bd-arc** [comment]
@dyaacov Well, I'm not used to RTL interfaces but I'm trying to foresee what would seem more "natural" to every user of this plugin. My understanding was that everything was reversed between LTR and RTL layouts.

You mentioned slides with timestamp. In a LTR layout, I would render the following ('X' marks the first active slide):
```
      X 
[1st of March] [1st of April] [1st of May]
```

Shouldn't it be the following with a RTL layout?
```
                                 X 
[1st of May] [1st of April] [1st of March]
```

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.
Feel free to continue discussion if needed.

**Comment by malashkevich** [comment]
Hi @bd-arc 
Big thanks for this lib man!
I want to reopen this one. I have the same issue as described on video above.
The bug appears only for android.
Seems like it's related to https://github.com/facebook/react-native/issues/11960
I was able to 'fix' it by adding following `contentContainerCustomStyle` to carousel:

```
 Platform.OS === 'android' ? {flexDirection: I18nManager.isRTL ? 'row-reverse' : 'row'} : {};
```
Probably you can take a look on this?

lib version: 3.2.3
rn: 0.47

**Comment by bd-arc** [comment]
Hi @malashkevich,

I'm quite surprised because if you take a look at [line 765 of the source code](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L765), you'll see that I'm already using such a fix (along with a few others that you can find in [this commit](https://github.com/archriss/react-native-snap-carousel/commit/6d9d459f1f42fefc0a69c0b224304cdf4361870c#diff-580e5b51e04540b35aed2cd2486a1a24))...

Would you mind testing with RN 0.48 and letting me know the outcome?

**Comment by bd-arc** [comment]
@malashkevich Also, can you try [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) and let me know if everything is properly displayed for you?

It was working properly on the miscellaneous RTL devices I've tested it on, but I might have overlooked something...

**Comment by amitassaraf** [comment]
I am just going to add the it took me a while to figure out this is related to RTL. So for SEO reasons Im gonna add that if you encounter flickering or snap flickering in the carousel then it is related to this issue. The solution by @malashkevich works.

**Comment by ducpt2** [comment]
i using "react-native-snap-carousel": "3.8.0" and the issue still appear, i am using @malashkevich solution to fix it. Maybe i miss something? Any help?
