### ISSUE TITLE
Slide does not initially show if component wrapped using `memo` API (on iOS device)

### ISSUE THREAD

**Issue by radiosilence** [archriss/react-native-snap-carousel#465]
### Is this a bug report, a feature request, or a question?

Bug report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - replace the space character between the square brackets (`[]`) by an `x`.)

- [x ] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?
Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

iOS 12.1.3

### Is the bug reproductible in a production environment (not a debug one)?

Yeah

### Environment

React: 16.6.3
React Native: 0.57.8
React Snap Caroursel: 3.7.5

### Expected Behavior

The slides would show

### Actual Behavior

The slides do not show until you move the carousel

### Reproducible Demo

Snack wasn't working on my shitty company internet

### Steps to Reproduce

 All you have to do is take any carousel and wrap the individual slide components in `memo`

**Comment by kbrandwijk** [comment]
@radiosilence I'm observing the same behavior. Did you close the issue because it was resolved on your end?

**Comment by radiosilence** [comment]
I closed it because I removed memo and it was still happening :(

**Comment by kbrandwijk** [comment]
I went over all the other issues, and finally found this one, that solved it for me: https://github.com/archriss/react-native-snap-carousel/issues/238#issuecomment-354528113

**Comment by radiosilence** [comment]
Ah, thanks so much! this solved it for me too 👍
