### ISSUE TITLE
Warning : Calling 'getNode()' on the ref an Animated Component is no longer necessary.

### ISSUE THREAD

**Issue by dilinade** [archriss/react-native-snap-carousel#672]
### Is this a bug report, a feature request, or a question?

Question

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

It is a warning regarding deprecation of the method `getNode()`. 

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

(Write your answer here and specify the iOS/Android versions on which you've been able to reproduce the issue.)

### Is the bug reproductible in a production environment (not a debug one)?

Yes.

### Environment

   React native: 0.62.0
    react-native-snap-carousel: 3.8.4

  Target Platform:
    Android (9.0)
    iOS (13.3)

### Expected Behavior

No warning should be raised. Upgrade is needed.

### Actual Behavior

Raise of a warning.
![image](https://user-images.githubusercontent.com/14290956/77842892-30cd4680-71b5-11ea-8ff1-7091f242f20b.png)

### Reproducible Demo

(Paste the link to a [Snack example](https://snack.expo.io/) in which the issue can be reproduced. Please follow [the guidelines](https://stackoverflow.com/help/mcve) for providing a Minimal, Complete, and Verifiable example.)

**Comment by ahsan-khan1999** [comment]
having same issue react-native v 0.61 occurs implementing nested navigation.

**Comment by lumberman** [comment]
Same problem. Came here from https://stackoverflow.com/questions/60910385/upgraded-to-react-native-0-62-0-getting-warning-sign-calling-getnode-on-t

**Comment by dilinade** [comment]
@lumberman Give #673 a try :)

**Comment by anthony-elhaddad** [comment]
same problem but im using the 'react-native-image-slider-box' which is using the carousel.

**Comment by binar1** [comment]
i fixed ,in this way,
 go to nodeModule -> react-native-snap-carousel -> src -> Carousel.js
modify 

const AnimatedFlatList = FlatList ? Animated.createAnimatedComponent(FlatList)    : null;
const AnimatedScrollView = Animated.Animated.createAnimatedComponent(ScrollView);

to
const AnimatedFlatList = FlatList ? Animated.FlatList    : null;
const AnimatedScrollView = Animated.ScrollView;

after find function _getWrappedRef  
modify to like this 
 _getWrappedRef () {
        // https://github.com/facebook/react-native/issues/10635
        // https://stackoverflow.com/a/48786374/8412141
        return this._carouselRef  
    }

then save it .
I Hope This can Help you

**Comment by anisharya16** [comment]
> i fixed ,in this way,
> go to nodeModule -> react-native-snap-carousel -> src -> Carousel.js
> modify
> 
> const AnimatedFlatList = FlatList ? Animated.createAnimatedComponent(FlatList) : null;
> const AnimatedScrollView = Animated.Animated.createAnimatedComponent(ScrollView);
> 
> to
> const AnimatedFlatList = FlatList ? Animated.FlatList : null;
> const AnimatedScrollView = Animated.ScrollView;
> 
> after find function _getWrappedRef
> modify like this
> _getWrappedRef () {
> // [facebook/react-native#10635](https://github.com/facebook/react-native/issues/10635)
> // https://stackoverflow.com/a/48786374/8412141
> return this._carouselRef
> }
> 
> then save it .
> I Hope This can Help you

Thankyou so much, It helped.

**Comment by akhan118** [comment]
Hi, any updates on when this will be release ?

**Comment by ltcaosj** [comment]
I am looking for the release too :)

**Comment by keiscool2468** [comment]
waiting for the release

**Comment by Yashah301** [comment]
waiting for release too

**Comment by fdelavra** [comment]
waiting for release too ;)

**Comment by heesienooi** [comment]
+1 waiting for the release

**Comment by celucode** [comment]
waiting for release too!

**Comment by bpdarlyn** [comment]
waiting for release too!

**Comment by xAgustin93** [comment]
¿Cuando se arreglara ese problema en el repositorio?

**Comment by didikk** [comment]
I am looking for the release too

**Comment by tinchev** [comment]
+1

**Comment by tinmar33** [comment]
+1

**Comment by diegovfeder** [comment]
Would love to see this 'acclaimed' release

**Comment by AJV2018** [comment]
Waiting....

**Comment by harmandeepsingh** [comment]
Yes waiting...

**Comment by philipeneves** [comment]
Waiting

**Comment by loverdeveloper** [comment]
Yes waiting...

**Comment by renishghetia** [comment]
Waiting for this release too

**Comment by ghasemikasra39** [comment]
waiting

**Comment by riamon-v** [comment]
waiting too..

**Comment by gegham-khachatryan** [comment]
waiting

**Comment by chahinaghrim** [comment]
waiting ..

**Comment by hussainhspl** [comment]
waiting

**Comment by ovy9086** [comment]
I don't know how all you guys commenting "waiting" here think will solve the problem. maybe stop polluting the thread with useless comments, and a 👍 should be enough.
I think it's clear enough until now that a lot of people are 'waiting' for this fix.

**Comment by pratyaksh123** [comment]
Why the PR is not merged yet?

**Comment by MrLoh** [comment]
Probably because it is really complicated to detect the RN package Version the right way.

**Comment by BhullarGagan** [comment]
> i fixed ,in this way,
> go to nodeModule -> react-native-snap-carousel -> src -> Carousel.js
> modify
> 
> const AnimatedFlatList = FlatList ? Animated.createAnimatedComponent(FlatList) : null;
> const AnimatedScrollView = Animated.Animated.createAnimatedComponent(ScrollView);
> 
> to
> const AnimatedFlatList = FlatList ? Animated.FlatList : null;
> const AnimatedScrollView = Animated.ScrollView;
> 
> after find function _getWrappedRef
> modify like this
> _getWrappedRef () {
> // [facebook/react-native#10635](https://github.com/facebook/react-native/issues/10635)
> // https://stackoverflow.com/a/48786374/8412141
> return this._carouselRef
> }
> 
> then save it .
> I Hope This can Help you


Thanks, This is also working with react-native-image-slider-box.... Thanks for help

**Comment by rikinshah23** [comment]
I am looking for the release too

**Comment by MrLoh** [comment]
Chill out and wait a little guys. It’s been 10 days not 10 months since the PR was filed and theres an ongoing discussion about the implementation. Either contribute or be patient. Open source doesn’t work by stressing contributors out but by contributing and being grateful for the contributions of others.

**Comment by bd-arc** [comment]
Ok, looks like [this is going to be fixed pretty soon](https://github.com/archriss/react-native-snap-carousel/pull/678#issuecomment-634085999)!

**Comment by bd-arc** [comment]
Fixed in versions `3.9.1` and `4.0.0-beta.4` with backward-compatible code.

**Comment by HarshitMadhav** [comment]
Hi! I reached out this thread when I faced this 'getNode()' warning and I was using `v3.9.0` and when I upgraded to `v3.9.1` it still shows the 'getNode()' warning.

```
    _getWrappedRef () {
        if (this._carouselRef && (
            (this._needsScrollView() && this._carouselRef.scrollTo) ||
            (!this._needsScrollView() && this._carouselRef.scrollToOffset)
        )) {
            return this._carouselRef;
        }
        // https://github.com/facebook/react-native/issues/10635
        // https://stackoverflow.com/a/48786374/8412141
        return this._carouselRef && this._carouselRef.getNode && this._carouselRef.getNode();
    }

```
I am running on react-native v 0.62.2

**Comment by HarshitMadhav** [comment]
In updated version I changed this
```
const AnimatedFlatList = FlatList ? Animated.createAnimatedComponent(FlatList) : null;
const AnimatedScrollView = Animated.Animated.createAnimatedComponent(ScrollView);

```
to this:
```
const AnimatedFlatList = FlatList ? Animated.FlatList : null;
const AnimatedScrollView = Animated.ScrollView;
```

as mentioned by @binar1 above

I think any how this change did not get pushed into the update.

**Comment by alejeindrox** [comment]
Current version 3.9.1 same problem

**Comment by AleksandrChyzhkov** [comment]
In the 3.9.1 release, the error did not disappear, so I used the @HarshitMadhav advice and with the help of patch-package fixed the problem so as not to wait for a new release. Thanks @HarshitMadhav !

**Comment by mikebertiean** [comment]
I can confirm that this warning has not been resolved

**Comment by dustinyoste** [comment]
Been using @dilinade's forked branch for this fix: https://github.com/dilinade/react-native-snap-carousel
Don't see any reason these changes shouldn't be merged.

**Comment by vgm8** [comment]
Tested this on react-native 0.63.4 and react-native-snap-carousel 3.9.1 and it is still happening

**Comment by PrsRares** [comment]
still happening. 0.63.3 and react-native-snap-carousel 3.9.1

**Comment by sjonchhe** [comment]
> Chill out and wait a little guys. It’s been 10 days not 10 months since the PR was filed and theres an ongoing discussion about the implementation. Either contribute or be patient. Open source doesn’t work by stressing contributors out but by contributing and being grateful for the contributions of others.

Well now its been more than 10 months and problem still exists...

**Comment by jaehyunjung83** [comment]
> 

this solved!!

**Comment by jaehyunjung83** [comment]
> i fixed ,in this way, go to nodeModule -> react-native-snap-carousel -> src -> Carousel.js modify
> 
> const AnimatedFlatList = FlatList ? Animated.createAnimatedComponent(FlatList) : null; const AnimatedScrollView = Animated.Animated.createAnimatedComponent(ScrollView);
> 
> to const AnimatedFlatList = FlatList ? Animated.FlatList : null; const AnimatedScrollView = Animated.ScrollView;
> 
> after find function _getWrappedRef modify like this _getWrappedRef () { // [facebook/react-native#10635](https://github.com/facebook/react-native/issues/10635) // https://stackoverflow.com/a/48786374/8412141 return this._carouselRef }
> 
> then save it . I Hope This can Help you


this will help!!!
